services:
  - type: web
    name: blog-platform-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: blog-platform-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
